[project]
name = "conversation-evaluator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.26",
    "ollama>=0.5.1",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.1",
]
